In [6]:
import numpy as np
import cv2

def convolucion(img, kernel):
    '''
    This function applies a convolution to an image
    '''
    alto = img.shape[0]
    ancho = img.shape[1]
    
    altoKernel = kernel.shape[0]
    anchoKernel = kernel.shape[1]

    # bucles
    for x in range(ancho):
        for y in range(alto):
            suma = 0
            for i in range(altoKernel):
                for j in range(anchoKernel):
                    if y + i - 1 >= 0 and x + j - 1 >= 0:
                        try:
                            suma += img[y + i - 1, x + j - 1] * kernel[i, j]
                        except:
                            pass
            img[y, x] = suma
    return img


# creemos una imagen de pixeles random para ejemplificar
imagen_ejemplo = np.random.randint(0, 255, (5, 5))
print(imagen_ejemplo)
# Dimensiones:
print(imagen_ejemplo.shape)

kernel_ej = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])
imagen_procesada = convolucion(imagen_ejemplo, kernel_ej)
print(imagen_procesada)
print(imagen_procesada.shape)

[[105  25  70 215 178]
 [158  89 252 202 198]
 [ 34   3 194 229  62]
 [102  65   4  99 152]
 [ 86 245  24  83  36]]
(5, 5)
[[    377    1499    6387   28119  131116]
 [    686    4149   20939  102621  516268]
 [    979    7812   46307  254152 1370429]
 [   1480   12679   83545  497174 2815671]
 [   1876   16308  112738  693728 4006609]]
