In [7]:
import numpy as np
import cv2

'''
pseudocodigo:
for each image row in input image:
    for each pixel in image row:
        set accumulator to zero
        for each kernel row in kernel:
            for each element in kernel row:
                if element position  corresponding to pixel position then
                    multiply element value  corresponding to pixel value
                    add result to accumulator
                endif
                    
        set output image pixel to accumulator
''' 
        
# Ahora traduzcamos este pseudocodigo a python

import numpy as np
import cv2

def convolucion(img, kernel):
    '''
    This function applies a convolution to an image
    '''
    alto = img.shape[0]
    ancho = img.shape[1]
    
    AltoKernel = kernel.shape[0]
    AnchoKernel = kernel.shape[1]

    # bucles
    for x in range(ancho):
        for y in range(alto):
            suma = 0
            for i in range(AltoKernel):
                for j in range(AnchoKernel):
                    if y + i - 1 >= 0 and x + j - 1 >= 0:
                        try:
                            suma += img[y + i - 1, x + j - 1] * kernel[i, j]
                        except IndexError:
                            pass
            img[y, x] = suma
    return img


# creemos una imagen de pixeles random para ejemplificar
imagen_ejemplo = np.random.randint(0, 255, (5, 5))
print(imagen_ejemplo)
# Dimensiones:
print(imagen_ejemplo.shape)

kernel_ej = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])
imagen_procesada = convolucion(imagen_ejemplo, kernel_ej)
print(imagen_procesada)
print(imagen_procesada.shape)


# imagen = cv2.imread('images/imagen.jpg', 0)

[[ 82 181 239  93 203]
 [239 120   8  34 169]
 [ 63 150 215 227 254]
 [109 107 121  73  57]
 [  4  86  61 175  35]]
(5, 5)
[[    622    2545   10117   44531  210563]
 [   1375    7198   33915  165660  835210]
 [   1924   13478   76210  414033 2228419]
 [   2380   20949  137468  813205 4591589]
 [   2577   26174  184900 1135840 6540669]]
(5, 5)
